[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[dependencies]
dyn-clone = "1.0.17"
nalgebra = { version = "0.32.3", features = ["serde-serialize"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

[dev-dependencies]
lazy_static = "1.4.0"
