name: pages-build-deploy
run-name: Build pages and deploy
on:
  push:
    branches:
      - master
jobs:
  build-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Lockfile
        run: cargo generate-lockfile
      - name: Get version
        run: echo "version=$(cargo pkgid | cut -d '#' -f2)" >> "$GITHUB_ENV"
      - name: Set version
        run: |
          echo "Setting version: $version"
          sed -i "s/<\$VERSION\$>/$version/" docs/user-manual/main.tex
      - name: Build Latex
        uses: dante-ev/latex-action@2021-A
        with:
          working_directory: docs/user-manual/
          root_file: main.tex
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: manual
          path: docs/user-manual/
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docs
        run: cargo doc --workspace --no-deps --document-private-items
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: docs
          path: target/doc
  build-jekyll:
    runs-on: ubuntu-latest
    needs: [build-manual, build-docs]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repository/
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Create Pages Directory
        run: |
          mkdir pages/
          mv manual/main.pdf pages/manual.pdf
          mv docs/ pages/docs/
          mv repository/README.md pages/index.md
          printf "name: POST\ntitle: null" > pages/_config.yml
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.12
        with:
          source: pages/
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
  deploy-pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-jekyll
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5