name: build-release
run-name: Build and Release
concurrency:
  group: deploy
  cancel-in-progress: true
on:
  workflow_run:
    workflows: test-lint
    types: completed
jobs:
  check-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Generate Lockfile
        run: cargo generate-lockfile
      - name: Get version
        id: get-version
        run: |
          version=$(cargo pkgid | cut -d '#' -f2)
          echo "Found version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Check if tag exists
        id: check-tag
        continue-on-error: true
        run: |
          echo "Checking v${{steps.get-version.outputs.version}}"
          git show-ref --tags --verify -- "refs/tags/v${{steps.get-version.outputs.version}}"
          echo "tag-exists=$?" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag-exists: ${{ steps.check-tag.outputs.tag-exists }}
  build-manual:
    needs: check-version
    runs-on: ubuntu-latest
    env:
      version: ${{ needs.check-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        run: |
          echo "Setting version: $version"
          sed -i "s/<\$VERSION\$>/$version/" docs/user-manual/manual.tex
      - name: Build Latex
        uses: dante-ev/latex-action@2021-A
        with:
          working_directory: docs/user-manual/
          root_file: manual.tex
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: manual
          path: docs/user-manual/manual.pdf
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docs
        run: cargo doc --workspace --no-deps --document-private-items
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: docs
          path: target/doc
  build-jekyll:
    needs: [build-manual, build-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repository/
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Create Pages Directory
        run: |
          mkdir pages/
          mv manual/manual.pdf pages/
          mv docs/ pages/docs/
          mv repository/README.md pages/index.md
          printf "name: POST\ntitle: null" > pages/_config.yml
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.12
        with:
          source: pages/
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
  deploy-pages:
    needs: build-jekyll
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
  build:
    needs: check-version
    if: ${{ !needs.check-version.outputs.tag-exists }}
    env:
      version: ${{ needs.check-version.outputs.version }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            runner: macOS-latest
            name: macOS-x86_64
          - target: aarch64-apple-darwin
            runner: macOS-latest
            name: macOS-aarch64
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            name: windows-x86_64
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            name: linux-x86_64
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
            name: linux-aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--workspace --release"
      - name: Create artifact directory
        id: create-dir
        shell: bash
        run: |
          mkdir artifact/
          mv LICENSE artifact/
          mv README.md artifact/
          mv utils/example.json artifact/
          mv utils/plot/ artifact/plotting-tool/

          if [ ${{ matrix.runner }} == "windows-latest" ]
          then
            mv target/${{ matrix.target }}/release/post.exe artifact/post-$version.exe
          else
            mv target/${{ matrix.target }}/release/post artifact/post-$version
          fi

          if [ ${{ matrix.runner }} == "ubuntu-latest" ]
          then
            name=post-$version-${{ matrix.name }}.tar.gz
            tar -czf $name artifact/
          else
            cd artifact/
            name=post-$version-${{ matrix.name }}.zip
            7z a -r ../$name *
          fi

          echo "artifact=$name" >> "$GITHUB_ENV"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.artifact }}
          path: ${{ env.artifact }}
    outputs:
      version: ${{ steps.create-dir.outputs.version }}
  release:
    needs: [build, build-manual]
    permissions:
      contents: write
    env:
      version: ${{ needs.build.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        run: |
          if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "Found invalid version '$version'" >&2
            exit 1
          fi
      - name: Make Directory
        run: mkdir artifacts/
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: post-*
          path: artifacts/
          merge-multiple: true
      - name: Download Manual
        uses: actions/download-artifact@v4
        with:
          name: manual
          path: artifacts/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          files: artifacts/*
          fail_on_unmatched_files: error

