name: build-release
run-name: Build and Release
on: workflow_dispatch
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Generate Lockfile
        run: cargo generate-lockfile
      - name: Get version
        id: get-version
        run: |
          version=$(cargo pkgid | cut -d '#' -f2)
          echo "Found version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Check if tag exists
        id: check-tag
        continue-on-error: true
        run: |
          echo "Checking ${{steps.get-version.outputs.version}}"
          git show-ref --tags --verify --quiet -- "refs/tags/v${{steps.get-version.outputs.version}}"
          echo "tag-exists=$?" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag-exists: ${{ steps.check-tag.outputs.tag-exists }}
  debug:
    runs-on: ubuntu-latest
    needs: [check-version]
    if: ${{ needs.check-version.outputs.tag-exists }}
    steps:
      - run: echo "Tag already exists"
  build:
    needs: [check-version]
    if: ${{ !needs.check-version.outputs.tag-exists }}
    env:
      version: ${{ needs.check-version.outputs.version }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            runner: macOS-latest
            name: macOS-x86_64
          - target: aarch64-apple-darwin
            runner: macOS-latest
            name: macOS-aarch64
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            name: windows-x86_64
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            name: linux-x86_64
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
            name: linux-aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--workspace --release"
      - name: Create artifact directory
        id: create-dir
        shell: bash
        run: |
          mkdir artifact/
          mv LICENSE artifact/
          mv README.md artifact/
          mv utils/example.json artifact/
          mv utils/plot/ artifact/plotting-tool/

          if [ ${{ matrix.runner }} == "windows-latest" ]
          then
            mv target/${{ matrix.target }}/release/post.exe artifact/post-$version.exe
          else
            mv target/${{ matrix.target }}/release/post artifact/post-$version
          fi

          if [ ${{ matrix.runner }} == "ubuntu-latest" ]
          then
            name=post-$version-${{ matrix.name }}.tar.gz
            tar -czf $name artifact/
          else
            cd artifact/
            name=post-$version-${{ matrix.name }}.zip
            7z a -r ../$name *
          fi

          echo "artifact=$name" >> "$GITHUB_ENV"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ artifact }}
          path: ${{ artifact }}
    outputs:
      version: ${{ steps.create-dir.outputs.version }}
  release:
    permissions:
      contents: write
    needs: build
    env:
      version: ${{ needs.build.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Make Directory
        run: mkdir artifacts/
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          files: artifacts/*

