name: build-test-lint
run-name: Build project, test and lint
on: push
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --workspace
      - name: Test
        run: cargo test --workspace
      - name: Lint
        run: cargo clippy --workspace