name: test-lint
run-name: Test and lint
on: push
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: cargo test --workspace
      - name: Lint
        run: cargo clippy --workspace